security:
  enable_authenticator_manager: true
  password_hashers:
    App\Entity\User: auto
  providers:
    users:
      id: App\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      stateless: false
      provider: users
      user_checker: ~
      custom_authenticator: App\Security\ApiAuthenticator
      logout:
        path: app_logout
  access_control:
    - { path: ^/, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
