image: phpdockerio/php73-fpm:latest

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update
            - apt-get install -y openssh-client
            - php bin/dep deploy prod
