version: "3.1"
services:
    grooming-chimps-web-webserver:
      image: nginx:alpine
      container_name: grooming-chimps-web-webserver
      working_dir: /application
      volumes:
        - ..:/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8091:80"
      depends_on:
        - grooming-chimps-web-php-fpm

    grooming-chimps-web-php-fpm:
      build: php-fpm
      container_name: grooming-chimps-web-php-fpm
      working_dir: /application
      volumes:
        - ..:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
